# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_dev
  username: portfolio_dev
  password: password123

test:
  <<: *default
  database: portfolio_test
  username: portfolio_test
  password: password1234



production:
  <<: *default
  database: portfolio_prod
  username: root
  password: password12345

